import Head from 'next/head';
import styled from 'styled-components';
import About from '../components/About';
import Banner from '../components/Banner';
import Community from '../components/Community';
import Social from '../components/Social';
import Nft from '../components/Nft';
import Option from '../components/Option';
import Questions from '../components/Questions';
import Road from '../components/Road';
import Footer from '../components/Footer';

export default function Home() {
  return (
      <Container>
          <Head>
          <title>Gababy NFT</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <Banner/>
          <Community/>
          <About/>
          <Nft/>
          <Road/>
          <Option/>
          <Questions/>
          <Social/>
          <Footer/>
      </Container>      
  )
}

const Container = styled.div``